pull_request_rules:
  - name: dep-condition-probe
    conditions:
      - base = main
      - depends-on = mergify-poc-gng/pw-check#2
    actions:
      label:
        add:
          - dep-listed
  - name: attempt-merge
    conditions:
      - base = main
    actions:
      merge:
        method: merge
